package View;

import java.awt.Color;
import javax.swing.BorderFactory;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rubén González V
 */
public class PanelRA extends javax.swing.JPanel {
    public int result;
    public String operation;
    public int number;
    public Boolean isFirst;
    
    public int up;
    public int down;
    public int left;
    public int right;

    /**
     * Creates new form Panel
     */
    public PanelRA(int result, String operation, int number, Boolean isFirst, int up, int down, int left, int right) {
        initComponents();
        this.result = result;
        this.operation = operation;
        this.number = number;
        this.isFirst = isFirst;
        this.up = up;
        this.down = down;
        this.left = left;
        this.right = right;
        jTextPane1.setText(String.valueOf(result)+operation+"\n"+String.valueOf(number));
//        labelNumber.setText(String.valueOf(number));
//        labelOperation.setText(String.valueOf(result)+operation);
        this.setBorder(BorderFactory.createMatteBorder(up, left, down, right, Color.BLACK));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(100, 100));

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
