package View;

import java.awt.Color;
import javax.swing.BorderFactory;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rubén González V
 */
public class PanelRA extends javax.swing.JPanel {
    public int result;
    public String operation;
    public int number;
    public Boolean isFirst;
    
    public int up;
    public int down;
    public int left;
    public int right;

    /**
     * Creates new form Panel
     */
    public PanelRA(int result, String operation, int number, Boolean isFirst, int up, int down, int left, int right) {
        initComponents();
        this.result = result;
        this.operation = operation;
        this.number = number;
        this.isFirst = isFirst;
        this.up = up;
        this.down = down;
        this.left = left;
        this.right = right;
        labelNumber.setText(String.valueOf(number));
        labelOperation.setText(String.valueOf(result)+operation);
        this.setBorder(BorderFactory.createMatteBorder(up, left, down, right, Color.BLACK));
    }

    public void changeText(String text)
    {
        labelOperation.setText(text);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelOperation = new javax.swing.JLabel();
        labelNumber = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(100, 100));

        labelOperation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelOperation.setText("Hola");

        labelNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNumber.setText("9");
        labelNumber.setMaximumSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(labelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(labelOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNumber;
    private javax.swing.JLabel labelOperation;
    // End of variables declaration//GEN-END:variables
}
